name: Shellcheck CI

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  workflow_dispatch:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        severity: error
        format: gcc
      env:
        SHELLCHECK_OPTS: -s bash
